const About = () => {
    return <div>This is Users About page</div>
}

export default About;

export const generateMetadata = () => {
    return {
        title: "Can Savcı Website",
        description: "Generated by Can Savcı"
    }
}